spring:
  application:
    name: Api-Gateway
  cloud:
    gateway:
      routes:
        - id: api-1
          uri: lb://Welcome-Service
          predicates:
            - Path=/welcome
        - id: api-2
          uri: lb://Greet-Service
          predicates:
            - Path=/greet
server:
  port: 3333


  main:
    web-application-type: reactive



